version: '3.3'
services:

  mysql:
    container_name: mamute-db
    image: mysql:5.7.4
    restart: always
    privileged: true
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: mamute
      MYSQL_USER: mamute
      MYSQL_PASSWORD: mamute

    networks:
      - mamute-net

  mamute:
    container_name: mamute
    image: local/mamute:1.5.0
    restart: always
    privileged: true
    environment:
      - MAMUTE_PORT=8080
    ports:
        - 8080:8080
    networks:
      - mamute-net

  # proxy:
  #   container_name: mamute-proxy
  #   # image: nginx:1.9
  #   image: local/mamute-proxy
  #   # restart: always
  #   privileged: true
  #   # volumes:
  #   #   #- /var/docker-storage/persistant/nginx:/etc/nginx:ro
  #   #   - nginx:/etc/nginx:ro
  #   ports:
  #     - 443:443
  #     - 80:80
  #   networks:
  #     - mamute-net

volumes:
  mysql-db:

networks:
  mamute-net:
    driver: bridge